# Generated by Django 3.2 on 2021-05-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_auto_20210527_1037"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Subscriber",
            new_name="Join",
        ),
    ]
