# Generated by Django 3.2 on 2021-06-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_order_special_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='special_instructions',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
    ]
