# Generated by Django 3.2 on 2021-06-01 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_auto_20210504_1001"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="smells_like",
        ),
    ]
